using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MovementScript : MonoBehaviour
{
    public float movementSpeed = 2f; // Velocidad de movimiento en el eje Y
    public float oscillationAmount = 0.5f; // Amplitud de oscilaci贸n
    public float oscillationSpeed = 2f; // Velocidad de oscilaci贸n

    private float initialY; // Posici贸n Y inicial del objeto

    void Start()
    {
        initialY = transform.position.y; // Guarda la posici贸n Y inicial
    }

    void Update()
    {
        // Movimiento en el eje Y
        float newY = Mathf.Sin(Time.time * oscillationSpeed) * oscillationAmount + initialY;
        transform.position = new Vector3(transform.position.x, newY, transform.position.z);

        // Movimiento constante en el eje Y
        transform.Translate(Vector3.up * Time.deltaTime * movementSpeed);
    }
}